// This file is auto-generated by @hey-api/openapi-ts

import type { Client, Options as Options2, TDataShape } from './client';
import { client } from './client.gen';
import type { SdkMerchantVerifyTokenData, SdkMerchantVerifyTokenErrors, SdkMerchantVerifyTokenResponses, SdkPhoneLoginData, SdkPhoneLoginErrors, SdkPhoneLoginResponses, SdkPhoneSendCodeData, SdkPhoneSendCodeErrors, SdkPhoneSendCodeResponses } from './types.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean> = Options2<TData, ThrowOnError> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: Record<string, unknown>;
};

/**
 * Verify user token for merchants
 *
 * Merchant API to verify user JWT token and get user information.
 * Requires merchant signature verification using app_secret.
 *
 * Signature algorithm: Using seaverse-go/signature SDK
 * - Signature headers: X-Timestamp, X-Nonce, X-Signature
 * - Signature is calculated using merchant's app_secret
 * - Merchant config is fetched from merchant-service
 *
 */
export const sdkMerchantVerifyToken = <ThrowOnError extends boolean = false>(options: Options<SdkMerchantVerifyTokenData, ThrowOnError>) => (options.client ?? client).post<SdkMerchantVerifyTokenResponses, SdkMerchantVerifyTokenErrors, ThrowOnError>({
    url: '/sdk/v1/merchant/verify-token',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Send SMS verification code
 *
 * Send a 6-digit SMS verification code to the phone number
 */
export const sdkPhoneSendCode = <ThrowOnError extends boolean = false>(options: Options<SdkPhoneSendCodeData, ThrowOnError>) => (options.client ?? client).post<SdkPhoneSendCodeResponses, SdkPhoneSendCodeErrors, ThrowOnError>({
    url: '/sdk/v1/auth/phone/send-code',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Phone login/register
 *
 * Login or register with phone number and SMS verification code.
 * - If phone number exists: Login
 * - If phone number is new: Auto-register and login
 * - May require invitation code based on configuration
 *
 */
export const sdkPhoneLogin = <ThrowOnError extends boolean = false>(options: Options<SdkPhoneLoginData, ThrowOnError>) => (options.client ?? client).post<SdkPhoneLoginResponses, SdkPhoneLoginErrors, ThrowOnError>({
    url: '/sdk/v1/auth/phone/login',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});
