// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: 'https://account-hub.sg.seaverse.dev' | 'http://localhost:8080' | (string & {});
};

export type MerchantVerifyTokenRequest = {
    /**
     * JWT access token to verify
     */
    token: string;
    /**
     * Merchant ID for signature verification
     */
    merchant_id: string;
};

export type MerchantVerifyTokenResponse = {
    success?: boolean;
    data?: {
        /**
         * User ID
         */
        user_id?: string;
        /**
         * Username
         */
        username?: string;
        /**
         * User email (if available)
         */
        email?: string;
        /**
         * User phone (if available)
         */
        phone?: string;
        /**
         * Merchant ID from token
         */
        merchant_id?: string;
        /**
         * Account status
         */
        status?: string;
    };
};

export type ErrorResponse = {
    success?: boolean;
    error?: string;
    code?: string;
};

export type PhoneSendCodeRequest = {
    /**
     * Phone number in E.164 format (e.g., +8613800138000)
     */
    phone: string;
    /**
     * Merchant ID (optional, defaults to "seaverse")
     */
    merchant_id?: string;
};

export type PhoneLoginRequest = {
    /**
     * Phone number in E.164 format
     */
    phone: string;
    /**
     * 6-digit SMS verification code
     */
    code: string;
    /**
     * Username for first-time registration (optional)
     */
    username?: string;
    /**
     * Invitation code (required if invite system is enabled)
     */
    invitation_code?: string;
    /**
     * Merchant ID (optional, defaults to "seaverse")
     */
    merchant_id?: string;
};

export type AuthSuccessResponse = {
    success?: boolean;
    message?: string;
    data?: {
        user?: AuthUserData;
        /**
         * JWT access token
         */
        token?: string;
        /**
         * JWT refresh token
         */
        refreshToken?: string;
    };
};

/**
 * Response when user registration requires invitation code
 */
export type TempUserResponse = {
    success?: boolean;
    message?: string;
    /**
     * Temporary user ID
     */
    tempUserId?: string;
    /**
     * User email (for email registration)
     */
    email?: string;
    /**
     * User phone (for phone registration)
     */
    phone?: string;
    requiresInvitationCode?: boolean;
    /**
     * Registration provider (email, phone, google, github, discord)
     */
    provider?: string;
};

export type AuthUserData = {
    user_id?: string;
    username?: string;
    email?: string;
    email_verified?: boolean;
    status?: 'active' | 'inactive' | 'suspended' | 'temp';
    /**
     * Map of OAuth provider to user ID
     */
    oauth_providers?: {
        [key: string]: string;
    };
    created_at?: string;
    updated_at?: string;
};

export type PageParam = number;

export type PageSizeParam = number;

export type AccountIdParam = string;

export type InviteIdParam = string;

export type SdkMerchantVerifyTokenData = {
    body: MerchantVerifyTokenRequest;
    headers: {
        /**
         * Unix timestamp in seconds
         */
        'X-Timestamp': string;
        /**
         * Random nonce string for replay protection
         */
        'X-Nonce': string;
        /**
         * Request signature generated using app_secret
         */
        'X-Signature': string;
    };
    path?: never;
    query?: never;
    url: '/sdk/v1/merchant/verify-token';
};

export type SdkMerchantVerifyTokenErrors = {
    /**
     * Bad request
     */
    400: ErrorResponse;
    /**
     * Invalid signature or token
     */
    401: ErrorResponse;
    /**
     * Internal server error
     */
    500: ErrorResponse;
};

export type SdkMerchantVerifyTokenError = SdkMerchantVerifyTokenErrors[keyof SdkMerchantVerifyTokenErrors];

export type SdkMerchantVerifyTokenResponses = {
    /**
     * Token verified successfully
     */
    200: MerchantVerifyTokenResponse;
};

export type SdkMerchantVerifyTokenResponse = SdkMerchantVerifyTokenResponses[keyof SdkMerchantVerifyTokenResponses];

export type SdkPhoneSendCodeData = {
    body: PhoneSendCodeRequest;
    headers: {
        /**
         * Application ID for multi-tenant routing
         */
        'X-App-ID': string;
    };
    path?: never;
    query?: never;
    url: '/sdk/v1/auth/phone/send-code';
};

export type SdkPhoneSendCodeErrors = {
    /**
     * Bad request
     */
    400: ErrorResponse;
    /**
     * Too many requests
     */
    429: ErrorResponse;
    /**
     * Internal server error
     */
    500: ErrorResponse;
};

export type SdkPhoneSendCodeError = SdkPhoneSendCodeErrors[keyof SdkPhoneSendCodeErrors];

export type SdkPhoneSendCodeResponses = {
    /**
     * Verification code sent successfully
     */
    200: {
        success?: boolean;
        message?: string;
        /**
         * Code validity in seconds
         */
        expires_in?: number;
    };
};

export type SdkPhoneSendCodeResponse = SdkPhoneSendCodeResponses[keyof SdkPhoneSendCodeResponses];

export type SdkPhoneLoginData = {
    body: PhoneLoginRequest;
    headers: {
        /**
         * Application ID for multi-tenant routing
         */
        'X-App-ID': string;
    };
    path?: never;
    query?: never;
    url: '/sdk/v1/auth/phone/login';
};

export type SdkPhoneLoginErrors = {
    /**
     * Bad request
     */
    400: ErrorResponse;
    /**
     * Unauthorized
     */
    401: ErrorResponse;
    /**
     * Internal server error
     */
    500: ErrorResponse;
};

export type SdkPhoneLoginError = SdkPhoneLoginErrors[keyof SdkPhoneLoginErrors];

export type SdkPhoneLoginResponses = {
    /**
     * Login/Register successful or invitation code required
     */
    200: AuthSuccessResponse | TempUserResponse;
};

export type SdkPhoneLoginResponse = SdkPhoneLoginResponses[keyof SdkPhoneLoginResponses];
